name: 'Build and deploy functions app to azure'

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_SUBSCRIPTIONID: ${{secrets.AZURE_SUBSCRIPTIONID}}
  PYTHON_VERSION: '3.11'

jobs:
    buildzip:
        runs-on: ubuntu-latest
        container:
          image: mcr.microsoft.com/azure-functions/python:4-python3.11-core-tools
        defaults:
          run:
            shell: bash
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: 'Install dependencies'
            run: |
              ls -a
              pip install -r ./requirements.txt
            

          - name: Azure Login SPN
            run: |
              az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID --allow-no-subscriptions
              az account set --subscription $AZURE_SUBSCRIPTIONID
            
          - name: Publish Zip
            run: |
              ls -a
              func azure functionapp publish azpoe-hecmonitor-anfquotaincrease --no-build --python 
          


        

    

          
    
    
              
            
    
            
                

        
        