name: 'Build and deploy functions app to azure'

on:
    push:
        branches:
            - updated-code
    workflow_dispatch:
env:         

    AZURE_FUNCTIONAPP_NAME: 'zonaldeployment-azpoe-function'   # set this to your function app name on Azure
    AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
    PYTHON_VERSION: '3.11'
jobs:
    build-and-deploy:
        runs-on: self-hosted
        defaults:
            run:
               shell: bash
        steps:
            - name: 'Checkout Github Actions'
              uses: actions/checkout@v4
            
            
                

        
        