name: 'Build and deploy functions app to azure'

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_SUBSCRIPTIONID: ${{secrets.AZURE_SUBSCRIPTIONID}}
  PYTHON_VERSION: '3.11'

jobs:
    azurelogin:
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: 'Setup Python environment'
            uses: actions/setup-python@v4
            with:
              python-version: ${{env.PYTHON_VERSION}}
          
          - name: 'Create Virtual env'
            run: |
              python -m venv .venv
              source .venv/bin/activate

          - name: 'Install dependenices'
            run: |
              pip install -r requirements.txt

          - name: 'Zip File'
            run: |
              zip -r functionapp.zip .
              ls -a
            
          - name: 'Upload Artifact'
            uses: actions/upload-artifact@v4
            with:
              name: functionappzip
              path: ./functionapp.zip


          
    
    
              
            
    
            
                

        
        