name: 'Build and deploy functions app to azure'

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_SUBSCRIPTIONID: ${{secrets.AZURE_SUBSCRIPTIONID}}

jobs:
    azurelogin:
        runs-on: ubuntu-latest
        container:
          image: mcr.microsoft.com/azure-cli:latest
        steps:
          - name: Azure Login SPN
            run: |
              az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID --allow-no-subscriptions
              az account set --subscription $AZURE_SUBSCRIPTIONID
    
    deploy:
        runs-on: ubuntu-latest
        needs: azurelogin
        container:
          image: python:3.11
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          
          - name: Setup Python env
            run: |
              python -m venv .venv  
              source .venv/bin/activate
            shell: bash
          
          - name: Install zip utility
            run: |
              apt-get update && apt-get install -y zip

          - name: Install Dependencies 
            run: |
              pip install -r requirements.txt

          - name: Zip file
            run: |
              curl -sL https://aka.ms/InstallAzureCLIDeb
              zip -r functionapp.zip .
            shell: bash

          - name: Deploy FunctionApp
            run: | 
              az functionapp deployment source config-zip \
                --resource-group "zonaldeployment-azpoe-rg" \
                --name "zonaldeployment-azpoe-function" \
                --src-path ./functionapp.zip
            
    
            
                

        
        