name: 'Build and deploy functions app to azure'

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_SUBSCRIPTIONID: ${{secrets.AZURE_SUBSCRIPTIONID}}
  PYTHON_VERSION: '3.11'

jobs:
    buildzip:
        runs-on: ubuntu-latest
        container:
          image: mcr.microsoft.com/azure-functions/python:4-python3.11-core-tools
        defaults:
          run:
            shell: bash
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Azure Login SPN
            run: |
              az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID --allow-no-subscriptions
              az account set --subscription $AZURE_SUBSCRIPTIONID
            
          - name: Deploy Function App
            run: |
              az functionapp config appsettings delete --name zonaldeployment-azpoe-function --resource-group zonaldeployment-azpoe-rg --setting-names WEBSITE_RUN_FROM_PACKAGE WEBSITE_USE_ZIP WEBSITE_CONTENTAZUREFILECONNECTIONSTRING WEBSITE_CONTENTSHARE
              func azure functionapp publish zonaldeployment-azpoe-function --python
          


        

    

          
    
    
              
            
    
            
                

        
        