name: 'Build and deploy functions app to azure'

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        container:
          image: mcr.microsoft.com/azure-cli:latest
        steps:
          - name: Azure Login SPN
            run: |
              az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID --allow-no-subscriptions
              az account show
            
            
                

        
        